---
title: "SDS 410: Project Proposal 2"
author: Selin Kubali
date: 1/29/2023
format: pdf
editor: source
---

## Sponsor

(100 words) In your own words, provide a brief description of the project sponsor organization here.
The Federal Reserve Bank of Cleveland is a regional Federal Reserve bank. It provides banking services to banks in the Fourth Federal Reserve District, which includes Cleveland, Cincinnati, Columbus, and Pittsburgh. It can store bank reserves and provide loans to banks. 

## Scope

(100-200 words) In your own words, describe the problem that will be addressed in this project, Also, provide a broad overview of how you might approach it. 
The project looks into the question of whether climate or weather events can influence how banks loan money. I would probably start by identifying a few broad questions I wanted to ask about the relationship between whether and loan data to see if there is anything worth investigating. Then I would choose topics to look into further and decide on a few more relationships to investigate. I'd want to format the project like this because with so much data, it would be easy to find spurious relationships by doing a lot of analyses. If I do find correlations, I would see if I could build a predictive model to understand future trends. 

## Vision

(100-200 words) In  your own words, describe what might result from this project. Be sure to describe both physical outputs *and the potential broader impacts of those outputs.* (e.g. how will they address problems/better society?) In this section, also describe, how your unique skills and interests can contribute to project success.  
I expect the project to result in data analyses that demonstrate which aspects of climate change affect lending. Ideally, we would be able to use this to predict how climate change will affect financial movements in the future. Banks and federal institutions could use this to manage their policies, if, for instance, they knew that demand for a certain kind of loan would go up in the near future. This might prevent some of the chaos associated with climate change.
I can contribute to this project because I am interested in weather and climate and have worked with climate data before. I also have plenty of experience with data wrangling and with creating predictive models, as well as a good understanding of what kinds of predictive models are appropriate to create based on the data available.